name: push-notion

on:
  repository_dispatch:
    types: [rates_updated]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      # Defaults (overridden by dispatch payload if present)
      PAGES_RATES_URL: https://taylorsudo.github.io/rba-aud-rates/rates-latest.json
      RAW_RATES_URL: https://raw.githubusercontent.com/taylorsudo/rba-aud-rates/main/public/rates-latest.json
      # Optional subset, e.g. "USD,EUR,JPY"
      # CURRENCY_FILTER: USD
    steps:
      - uses: actions/checkout@v4

      - name: Resolve rates URL (Pages → raw fallback)
        run: |
          set -euo pipefail
          URL="${{ github.event.client_payload.rates_url || env.PAGES_RATES_URL }}"
          if ! curl -fsI "$URL" >/dev/null; then
            echo "Pages URL not reachable, falling back to RAW."
            URL="${RAW_RATES_URL}"
          fi
          echo "RATES_JSON_URL=$URL" >> "$GITHUB_ENV"

      - name: Push latest rates to Notion
        run: |
          python3 scripts/push_latest.py
