name: push-notion

on:
  repository_dispatch:
    types: [rates_updated]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      # default if payload missing; overridden below if present
      RATES_JSON_URL: https://taylorsudo.github.io/rba-aud-rates/rates-latest.json
      # Optional: CURRENCY_FILTER: USD,EUR,JPY
    steps:
      - uses: actions/checkout@v4

      - name: Prefer payload URL if provided
        run: |
          if [ -n "${{ github.event.client_payload.rates_url }}" ]; then
            echo "RATES_JSON_URL=${{ github.event.client_payload.rates_url }}" >> $GITHUB_ENV
          fi

      - name: Log payload (debug)
        run: |
          echo "rates_url = ${{ github.event.client_payload.rates_url }}"
          echo "history_url = ${{ github.event.client_payload.history_url }}"
          echo "date = ${{ github.event.client_payload.date }}"
          echo "RATES_JSON_URL (effective) = ${RATES_JSON_URL}"

      - name: Push to Notion
        run: |
          python3 scripts/push_to_notion.py
